version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
    container_name: existera-tech
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
