version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: existera-tech
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
